### ISSUE TITLE
Easier way of launching Apps

### ISSUE THREAD

**Issue by finnmglas** [finnmglas/Launcher#11]
Right now it is hard to open apps (which may annoy some users) and there is no application search included (Except Finder, which is external and not easy to set up).

---

**Ideas:**
+ Swiping from the top down will open a custom app menu?
+ Make easier to open finder?
+ Double tap action to open app menu? (even though I didn't want to constrain any methods of interaction)

---

*If you have more ideas about that or find this issue useful just comment below*

**Comment by goodevilgenius** [comment]
FWIW, I bound Double Click to open [Jina App Drawer](https://jinadrawer.com/).

Maybe a better solution than integrating an app drawer directly into the app would be to suggest third-party app drawers that could be used from within Launcher. There are probably multiple apps that already provide the functionality.
