### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by goodevilgenius** [finnmglas/Launcher#44]
**Is your feature request related to a problem? Please describe.**

Google Play is not available on several non-Google-certified devices, and many people prefer to get applications outside of Google's ecosystem.

**Describe the solution you'd like**

[F-Droid](https://f-droid.org/) is a third-party Android repository for open source applications. Publishing Launcher there would allow those who prefer not to use Google Play Services to still use the app.

**Describe alternatives you've considered**

Installing the apk from the Releases page is an alternative, but it requires the end-user to ensure that the app stays up-to-date. Publishing to F-Droid would allow the end-user to be notified when an update is available.

**Additional info**

- [How do I submit my app to F-Droid?](https://f-droid.org/forums/topic/how-can-i-submit-my-app-to-f-droid/)

There is also another F-Droid compatible repo with less stringent criteria for inclusion at https://android.izzysoft.de/repo/info. IzzyOnDroid publishes directly from apks on GitHub releases.

**Comment by finnmglas** [comment]
Thank you! I will make it available from F-Droid too ^^

For now, I requested IzzyOnDroid to publish the apks from the [Launcher GitHub releases][1].

-> [Related issue on GitLab][2]

[1]: https://github.com/finnmglas/Launcher/releases
[2]: https://gitlab.com/IzzyOnDroid/repo/-/issues/94

**Comment by IzzySoft** [comment]
Thanks for reaching out! I'm just in the process of adding your app. You will notice I've cropped your screenshots; that's done respecting the small screen estate on mobile phones, so users have a chance to recognize something on the pictures without trouble, especially when browsing via the F-Droid app.

For publishing on F-Droid, you might wish to establish [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo (just the files, the binaries are not needed).

OK, processing finished – your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.finnmglas.launcher) within less than 24h (I've just missed today's sync, too much to do), with English and German description, as you provided. If you wish to link there from next to the Play Store badge, you can [find a matching one here](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it). Updates will be fetched automatically within 24h of your tagging and attaching an APK (usually around 7:30 pm CE(S)T).

**Comment by IzzySoft** [comment]
PS: I'd say your app should meet the inclusion criteria for "the big repo" as well – so if you wish, go ahead and [open an RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging) once Fastlane is ready and tagged. It's not that difficult, and I'll pick up from there (disclosure: I'm one of the F-Droid maintainers).

Oh, and thanks for adding the badge! :smiling_face_with_three_hearts:

**Comment by finnmglas** [comment]
Created a RFP: https://gitlab.com/fdroid/rfp/-/issues/1377

@IzzySoft - Are the fastlane structures okay?

**Comment by IzzySoft** [comment]
Almost. The changelog for the current release would be `7.txt` (i.e. `<versionCode>.txt` – no idea where you took the `111.txt` name from… wait, you wouldn't have converted that to bin, would you? Oh my, took me a minute to figure :rofl: No, please stick to the decimal system). Else it looks fine – thanks for also adding the screenshots!

One thing I'm missing is `de-DE` in Fastlane: wanna take the contents of 
[com.finnmglas.launcher_de.zip](https://github.com/finnmglas/Launcher/files/4738465/com.finnmglas.launcher_de.zip) for that?

**Comment by finnmglas** [comment]
We're on the official f-droid site!

https://f-droid.org/packages/com.finnmglas.launcher/

**Comment by IzzySoft** [comment]
I'd say I give the folks a few days to notice before I remove the app from my repo then (unless you specifically want me to keep it here, that is)?

**Comment by finnmglas** [comment]
Yeah just leave it in there for a few days - thank you for your time and for having Launcher in the repo!
