### ISSUE TITLE
Feature: Option to enable / disable screen timeout (toggle)

### ISSUE THREAD

**Issue by ghost** [finnmglas/Launcher#54]
**Description**
The launcher doesn't honor the android system screen timeout, thus the screen stays on indefinitely if the user doesn't manually turn off his device. 

**To Reproduce**
1. Open the launcher
2. Wait for set screen timeout
3. Don't see the screen turn off

**Expected behavior**
The screen should turn off. duh.

**Smartphone**
Tested on the Android Studio VM (Pixel 3a API 30 x86) and on real hardware (H870 A10 custom ROM)

**Additional info**
This launcher is AMAZING, keep up the good work. I will take definitely take a closer look at the source code if i find time.

**Comment by finnmglas** [comment]
**Thank you for your feedback!**

The screen timeout used to be disabled on purpose,
as I often used Launcher at school or while working
and wanted it to stay ready / running at all times.
(With the [_dark theme_][dark-theme] many people think the device is turned off
with the always on display running ^^)

![A meme: bug or feature?][meme-picture]

**How will we solve it?**

As some people may need this functionality and others don't,
I believe it should be disabled by default with the option to enable it from settings.

**Related code (2020-06-21, will change after the fix)**
- The settings (where the option to enable/ disable the timeout will be): [`com.finnmglas.launcher.settings`][settings-dir]
- This is the line disabling the screen timeout: [`interface UIObject line 15`][screen-on-line]

[settings-dir]: https://github.com/finnmglas/Launcher/tree/master/app/src/main/java/com/finnmglas/launcher/settings
[screen-on-line]: https://github.com/finnmglas/Launcher/blob/ba6e29d1e360d52cf2e1c02d8ef39e9af6835cbd/app/src/main/java/com/finnmglas/launcher/UIObject.kt#L15

[dark-theme]: https://github.com/finnmglas/Launcher/tree/master/docs#dark-theme
[meme-picture]: https://cdn.netzpolitik.org/wp-upload/not-sure-if-this-is-a-bug-or-a-feature.png

**Comment by ghost** [comment]
Wow, thanks for this detailed reply. Since my phone has a normal IPS LCD display, having the display always on will probably kinda kill my battery. On an OLED device it really is an awesome setting if you use a black wallpaper/theme :D

**Comment by finnmglas** [comment]
Update: With many other features ^^, this will be included in version 1.3.0, which I will release in the next week (before July)
