### ISSUE TITLE
Since which Android version works the app?

### ISSUE THREAD

**Issue by Porrumentzio** [finnmglas/Launcher#71]

**Comment by finnmglas** [comment]
Hello @Porrumentzio !

The minimal Android API Version is defined in `app/build.gradle#L11` ([view file](https://github.com/finnmglas/Launcher/blob/v1.5.0/app/build.gradle#L11)) - currently it is `API 16`, equal to [Android 4.1](https://developer.android.com/studio/releases/platforms#4.1) or _Android Jelly Bean_, which was released in 2012.

I hope this is what you were asking for!

**Comment by finnmglas** [comment]
**Note** that Launcher may work on earlier Android versions if you decide to build the App for them (using Android Studio). There also are differences in how the app works across different APIs:

+ Android KitKat is required to control the device's AudioPlayer
+ The UI Color adjustments do not work the same on every API, for older ones, buttons colors cannot be set in runtime
+ Some Android versions do not work well with other system calls in the app...

Generally, I try to handle every possible exception in a helpful way, but if you encounter an API-specific error, make sure to open an issue for that : )

**Comment by finnmglas** [comment]
_As this is a question-issue, I am going to close it once you feel like I answered it in a helpful way_ :+1:

**Comment by Porrumentzio** [comment]
Perfect, thanks for the answer, great app!
