### ISSUE TITLE
More sensitivity for 'slide' function

### ISSUE THREAD

**Issue by ghost** [finnmglas/Launcher#73]
**The launcher's swiping function works when drawn perpendicularly only,for every time when you try to open the app using the swipe function, you will have to draw it perpendicularly .So it should have more flexibility for daily use.**

**Comment by finnmglas** [comment]
<sub>(As @nalinalini an me discussed earlier on Twitter)</sub>

---

In launchers source there actually is a **sensitivity value** - however, it has been set to a constant value that worked well with devices I used for testing.

The already implemented sensitivity value describes at which maximal angle swipe gestures will be recognized as such.

I feel like implementing a slider option in settings to control this sensitivity value would be an appropriate solution to this issue.

**Comment by finnmglas** [comment]
I solved this issue by implementing a slider that may adjust the apps sensitivity for swipe gestures:

![screenshot](https://user-images.githubusercontent.com/40366035/96450728-deb64600-1216-11eb-8421-9f0da17dfd12.png)

Changes will be included in the next release, either `v1.6.0` or `v1.5.1`!
