### ISSUE TITLE
Add a setting to not launch the keyboard when opening the app drawer

### ISSUE THREAD

**Issue by ghost** [finnmglas/Launcher#81]
I just started using this launcher and love it the only thing I have an issue with is that the keyboard opens up with the app drawer. While I'm sure this is intended behavior could you add a setting that allows you to disable that behavior.

**Comment by finnmglas** [comment]
It indeed was intended functionality as I disliked having to click the search bar all the time...
You'll see that it is disabled in the "choose app" app drawer / dialog.

Smart idea though, making this behaviour optional - we'll implement that!

I feel like this can be implemented by adding another switch to the `Launcher` tab of settings.

_Don't worry, I'll get to it, likely on the weekend - I am just very busy studying physics during the week : )_
