### ISSUE TITLE
Wallpaper removing itself

### ISSUE THREAD

**Issue by Crowerade** [finnmglas/Launcher#88]
The problem is that the wallpaper I chose for the launcher regularly removes itself and the launcher goes back to a grey background. Then I chose another time a wallpaper for the launcher and it stays for a moment, but after that it disappears.

**Comment by wolfn1337** [comment]
I have a similar problem: when i reboot my phone my custom Background gets reset.

**Comment by finnmglas** [comment]
I just observed the same behaviour (for the first time). I never noticed the bug as I used the dark theme and didn't reboot my phone in months.

Thanks for reporting the problem, I'll publish a patch to the PlayStore and F-Droid ASAP : )
